import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Toaster} from "@/components/ui/sonner";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { usePathname} from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Personal Finance Tracking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center p-24">
          {children}
        </main>
        <Toaster/>
      </body>
    </html>
  );
}
